name: export-image
on:
  push:
env:
  assets-branch: assets
  repo: kdash
  url: Bruce0203/kdash
jobs:
  export-image:
    # runs-on: self-hosted
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23
        with:
          files: |
            *.piskel
      - name: mkdirs assets directory
        run: mkdir assets
      - name: clone piskel-cli repo
        run: |
          git clone https://github.com/Bruce0203/piskel-cli
          cd piskel-cli
          npm install 
      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            node piskel-cli/index.js $file --pixiMovie true --output ./assets/$file --scaledWidth 512 --scaledHeight 512
          done
          rm -r piskel-cli
      - run: |
          echo ${{ github.actor }}
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.url }}
      - name: Run step if any of the listed files above is deleted
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ -f $file ]; then
              rm -r ${{ env.repo }}/assets/$file
            fi
          done
      - name: Run step if any of the listed files above is deleted
        if: steps.changed-files.outputs.any_deleted == 'true'
        run: |
          for file in ${{ steps.changed-files.outputs.deleted_files }}; do
            if [ -f $file ]; then
              rm -r ${{ env.repo }}/assets/$file
            fi
          done
      - run: |
          for file in assets; do
            cp -r $file ${{ env.repo }}/assets
          done
          cd ${{ env.repo }}
          git add .
          git commit -m "change assets"
          git push origin