name: export-image
on:
  push:
env:
  assets-branch: assets
  repo: kdash
  url: Bruce0203/kdash
jobs:
  export-image:
    runs-on: self-hosted
    # strategy:
      # matrix:
        # os: [ ubuntu-latest ]
    # runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: mkdirs assets directory
        run: mkdir assets
      - name: clone piskel-cli repo
        run: |
          git clone https://github.com/Bruce0203/piskel-cli
          cd piskel-cli
          npm install 
      - name: List all changed files
        run: |
          for file in *.piskel; do
            node piskel-cli/index.js $file --pixiMovie true --output ./assets/$file --scaledWidth 512 --scaledHeight 512
          done
          rm -r piskel-cli
      - run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git clone https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ env.url }}
      - run: |
          rm -r -f ${{env.repo}}/assets
          mkdir -p ${{env.repo}}/assets
          for file in ./assets/; do
            echo $file
            cp -r $file ${{env.repo}}/
          done
          cd ${{ env.repo }}
          git add .
          git commit -m "change assets"
          git push origin